server.port=${PORT:8080}
spring.application.name=booking-service

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${PGUSER:postgres}
spring.datasource.password=${PGPASSWORD:}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

cors.allowed-origins=${CORS_ALLOWED_ORIGINS:https://maxibottazzi.de}
owner.email=${OWNER_EMAIL:maxidigital@gmail.com}
email.service.url=${EMAIL_SERVICE_URL:http://underwater.railway.internal/send/internal}
